apiVersion: apps/v1
kind: Deployment
metadata:
  name: part1exercise1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: part1exercise1
  template:
    metadata:
      labels:
        app: part1exercise1
    spec:
      containers:
        - name: part1exercise1
          image: altrof/devops_kubernetes_course:1.1