apiVersion: v1
kind: Service
metadata:
  name: part1exercise5-svc
spec:
  type: NodePort
  selector:
    app: part1exercise5
  ports:
    - name: http
      nodePort: 30080
      protocol: TCP
      port: 1234
      targetPort: 80 # this port from nginx